mysql:
  host: '192.168.1.6'
  port: 3306
  user: root
  password: root
  db: mall_user



host: '192.168.0.104'
port: 8849
namespace: '6af9810f-2e08-4e9e-ab52-ae2868fe5fcc'
user: 'nacos'
password: 'nacos'
dataid: 'user-srv.json'
group: 'dev'